//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAlex.PowerCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAlex.PowerCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all traces?.
        /// </summary>
        internal static string DeleteAllTraces2DQuestion {
            get {
                return ResourceManager.GetString("DeleteAllTraces2DQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more circular references were found.
        ///FYI: A circular reference is a part of expression that refers to its own cell value, or refers to cell dependent on its own cell value..
        /// </summary>
        internal static string EXC_CircularReference {
            get {
                return ResourceManager.GetString("EXC_CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of matrix is invalid..
        /// </summary>
        internal static string EXC_InvalidFormatMatrix {
            get {
                return ResourceManager.GetString("EXC_InvalidFormatMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of matrix is invalid. Each opening bracket should have corresponding closing bracket..
        /// </summary>
        internal static string EXC_InvalidFormatMatrixBracketMatching {
            get {
                return ResourceManager.GetString("EXC_InvalidFormatMatrixBracketMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of matrix is invalid. Each closing bracket should have corresponding opening bracket..
        /// </summary>
        internal static string EXC_InvalidFormatMatrixClosingBracketMatching {
            get {
                return ResourceManager.GetString("EXC_InvalidFormatMatrixClosingBracketMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of matrix is invalid. Matrix should be enclosed with curly brackets..
        /// </summary>
        internal static string EXC_InvalidFormatMatrixCurlyBrackets {
            get {
                return ResourceManager.GetString("EXC_InvalidFormatMatrixCurlyBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of matrix is invalid. Last item should be not empty..
        /// </summary>
        internal static string EXC_InvalidFormatMatrixLastItem {
            get {
                return ResourceManager.GetString("EXC_InvalidFormatMatrixLastItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of matrix is invalid. All rows should be the same length..
        /// </summary>
        internal static string EXC_InvalidFormatMatrixRowLengths {
            get {
                return ResourceManager.GetString("EXC_InvalidFormatMatrixRowLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of the cell is out of range of the resultant matrix..
        /// </summary>
        internal static string EXC_MatrixIndexOutOfRange {
            get {
                return ResourceManager.GetString("EXC_MatrixIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.chm.
        /// </summary>
        internal static string HelpFileName {
            get {
                return ResourceManager.GetString("HelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.talex-soft.com.
        /// </summary>
        internal static string HomepageUrl {
            get {
                return ResourceManager.GetString("HomepageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerCalc.
        /// </summary>
        internal static string MessageBoxCaptionText {
            get {
                return ResourceManager.GetString("MessageBoxCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:support@talex-soft.com.
        /// </summary>
        internal static string SupportEmail {
            get {
                return ResourceManager.GetString("SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is assigned with value:.
        /// </summary>
        internal static string VariableValueAssigned {
            get {
                return ResourceManager.GetString("VariableValueAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array must be rectangular..
        /// </summary>
        internal static string WARN_ArrayMustBeRectangular {
            get {
                return ResourceManager.GetString("WARN_ArrayMustBeRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change part of an array..
        /// </summary>
        internal static string WARN_CannotChangePartOfArray {
            get {
                return ResourceManager.GetString("WARN_CannotChangePartOfArray", resourceCulture);
            }
        }
    }
}
