//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAlex.PowerCalc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int ZeroThreshold {
            get {
                return ((int)(this["ZeroThreshold"]));
            }
            set {
                this["ZeroThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G4")]
        public string NumericFormat {
            get {
                return ((string)(this["NumericFormat"]));
            }
            set {
                this["NumericFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string ColorScheme {
            get {
                return ((string)(this["ColorScheme"]));
            }
            set {
                this["ColorScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ComplexThreshold {
            get {
                return ((int)(this["ComplexThreshold"]));
            }
            set {
                this["ComplexThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF0F8FF")]
        public global::System.Windows.Media.Color Plot2DBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["Plot2DBackground"]));
            }
            set {
                this["Plot2DBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState WindowState {
            get {
                return ((global::System.Windows.WindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect WindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["WindowBounds"]));
            }
            set {
                this["WindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Extensions")]
        public string ExtensionsPath {
            get {
                return ((string)(this["ExtensionsPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int WorksheetMaxMatrixRows {
            get {
                return ((int)(this["WorksheetMaxMatrixRows"]));
            }
            set {
                this["WorksheetMaxMatrixRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int WorksheetMaxMatrixColumns {
            get {
                return ((int)(this["WorksheetMaxMatrixColumns"]));
            }
            set {
                this["WorksheetMaxMatrixColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int MatricesWorksheetRows {
            get {
                return ((int)(this["MatricesWorksheetRows"]));
            }
            set {
                this["MatricesWorksheetRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int MatricesWorksheetColumns {
            get {
                return ((int)(this["MatricesWorksheetColumns"]));
            }
            set {
                this["MatricesWorksheetColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF696969")]
        public global::System.Windows.Media.Color Plot2DForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["Plot2DForeground"]));
            }
            set {
                this["Plot2DForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFC0C0C0")]
        public global::System.Windows.Media.Color Plot2DGridlinesColor {
            get {
                return ((global::System.Windows.Media.Color)(this["Plot2DGridlinesColor"]));
            }
            set {
                this["Plot2DGridlinesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA9A9A9")]
        public global::System.Windows.Media.Color Plot2DAxisColor {
            get {
                return ((global::System.Windows.Media.Color)(this["Plot2DAxisColor"]));
            }
            set {
                this["Plot2DAxisColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#963399FF")]
        public global::System.Windows.Media.Color Plot2DSelectionRegionColor {
            get {
                return ((global::System.Windows.Media.Color)(this["Plot2DSelectionRegionColor"]));
            }
            set {
                this["Plot2DSelectionRegionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plot2DVertGridlinesVisible {
            get {
                return ((bool)(this["Plot2DVertGridlinesVisible"]));
            }
            set {
                this["Plot2DVertGridlinesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plot2DHorizGridlinesVisible {
            get {
                return ((bool)(this["Plot2DHorizGridlinesVisible"]));
            }
            set {
                this["Plot2DHorizGridlinesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plot2DXAxisVisible {
            get {
                return ((bool)(this["Plot2DXAxisVisible"]));
            }
            set {
                this["Plot2DXAxisVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plot2DYAxisVisible {
            get {
                return ((bool)(this["Plot2DYAxisVisible"]));
            }
            set {
                this["Plot2DYAxisVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHowToOnStartup {
            get {
                return ((bool)(this["ShowHowToOnStartup"]));
            }
            set {
                this["ShowHowToOnStartup"] = value;
            }
        }
    }
}
